### ISSUE TITLE
Deprecate and archive BCDevOps/go-crond

### ISSUE THREAD

**Issue by rajpalc7** [BCDevOps/backup-container#102]
Migration complete, however it requires some additional documentation updates to remove the references to BCDevOps in:

- https://github.com/BCDevOps/backup-container/blob/b8788694b836087adef4e299c51022b6c83248a3/docker/Dockerfile_MSSQL
- https://github.com/BCDevOps/backup-container/blob/b8788694b836087adef4e299c51022b6c83248a3/docker/Dockerfile_Mongo
- https://github.com/BCDevOps/backup-container/blob/b8788694b836087adef4e299c51022b6c83248a3/docker/Dockerfile_MariaDB

**Comment by WadeBarnes** [comment]
Complete
