### ISSUE TITLE
Update cron job to use  apiVersion: "batch/v1"

### ISSUE THREAD

**Issue by pbolduc** [BCDevOps/backup-container#104]
Kubernetes introduced `batch/v1` API version in 1.21. The `batch/v1beta1` API version of CronJob is no longer served as of v1.25. The next version of OpenShift, 4.12 uses Kubernetes 1.25. OpenShift 4.12 was released around February 1, 2023. It will be the next version deployed to BC Gov OpenShift at sometime in the future. To avoid uses of this backup container breaking, it should move to using the new API version. 

See: [Deprecated API Migration Guide 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)

**Comment by WadeBarnes** [comment]
@LawrenceLau2020, is this related to the message you sent me?

**Comment by WadeBarnes** [comment]
@pbolduc, @LawrenceLau2020, Feel free to make the updates, test things out, and submit a PR.  This is a community driven project.

**Comment by pbolduc** [comment]
It is a simple change, however, I currently do not have a deployment in place to test. I mainly created the issue to bring the removal to the attention of those who do have this deployment.

**Comment by WadeBarnes** [comment]
@LawrenceLau2020, do you have a place to test this?

**Comment by LawrenceLau2020** [comment]
Yes, we might be able to test this in our dev environment in OCP.

**Comment by WadeBarnes** [comment]
After a little investigation with @LawrenceLau2020, it turns out his concern is not related to the upgrade of the k8s version affecting the CronJob API version, but with the API version of a Tekton task they're using with the backup container.  Separate component, separate release schedule ... separate concern.

**Comment by pbolduc** [comment]
Right now, OCP Silver is running OpenShift 4.11 which uses Kubernetes v1.24.6. OpenShift 4.12, released on Feb 28, 2023, uses Kubernetes v1.25.4. In this next release, API batch/v1beta1 is no longer served. Any cron jobs using it will fail when the platform services deploys OpenShift 4.12 later this year.

**Comment by WadeBarnes** [comment]
PR submitted with the update.
