### ISSUE TITLE
Docker build issue for release 2.6.1

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/backup-container#109]
The dockerfile line 35 "RUN dnf install -y util-linux" complains dnf command not found during the build on Openshift. I replace with yum, and it passed.

**Comment by WadeBarnes** [comment]
It sounds like you're overriding default base image in your builds and not using the latest fedora based image; https://github.com/BCDevOps/backup-container/blob/master/docker/Dockerfile#L2.  Is your build still using a redhat based Postgres image as it's base?

**Comment by WadeBarnes** [comment]
I had this same issue when I first build the image on OpenShift and my build was still referencing the previous redhat based image which was overriding the `FROM` command in the docker file and replacing the `quay.io/fedora/postgresql-14:14` with the previous used redhat image.

**Comment by kuanfandevops** [comment]
close. have to add BASE_IMAGE_FOR_BUILD=quay.io/fedora/postgresql-14:14  when process the build template on Openshift otherwise it will use centos12
