### ISSUE TITLE
Verification error for release 2.6.1

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/backup-container#111]
We are using Posthresql v14. I encountered the verification error as below

sh-5.2$ ./backup.sh -s -v all

Verifying backup ...

Settings:
- Database: postgres=zeva-spilo-test:5432/zeva
- Backup file: /backups/2023-04-21/zeva-spilo-test-zeva_2023-04-21_15-22-37.sql.gz

Already clean ...

waiting for server to start.................
The server started in 0h:0m:21s.

Restoring from backup ...
waiting for server to shut down.... done
server stopped
Cleaning up ...

[!!ERROR!!] - Backup verification failed: /backups/2023-04-21/zeva-spilo-test-zeva_2023-04-21_15-22-37.sql.gz

The following issues were encountered during backup verification;
Restoring '/backups/2023-04-21/zeva-spilo-test-zeva_2023-04-21_15-22-37.sql.gz' to '127.0.0.1/zeva' ...

ERROR:  could not open extension control file "/usr/share/pgsql/extension/pg_stat_kcache.control": No such file or directory

Restore failed.

Elapsed time: 0h:0m:26s - Status Code: 3

**Comment by WadeBarnes** [comment]
@kuanfandevops, This looks like an extension you've added to your Postgres servers, you'll need to add the same extension to the backup server image.  I suspect you added it to the previous version of your backup-container image if you were not getting this error message before.

**Comment by kuanfandevops** [comment]
The pg_stat_kcache extension requires pg_stat_kcache package installed in system, but Fedora doesn't have it. I tried to build it from source [pg_stat_kcache](https://github.com/powa-team/pg_stat_kcache), it wasn't successful. I'll try to skip the verification step and directly try the store.
Close this issue.
