### ISSUE TITLE
Incorrect documentation for section: "Example of a Postgres deployment" 

### ISSUE THREAD

**Issue by pankaj-cgi** [BCDevOps/backup-container#112]
Documentation (https://github.com/BCDevOps/backup-container#example-deployments) suggests to run this command for generating an image:

oc -n 599f0a-tools process -f ./openshift/templates/backup/backup-build.json \
  -p NAME=nrmsurveys-bkup OUTPUT_IMAGE_TAG=v1 | oc -n 599f0a-tools create -f -

But there is no file /openshift/templates/backup/backup-build.json in the code base.

**Comment by WadeBarnes** [comment]
The templates got converted to `yaml`.  The file is here; https://github.com/BCDevOps/backup-container/blob/master/openshift/templates/backup/backup-build.yaml
