### ISSUE TITLE
How to verify/restore backups created by CronJob

### ISSUE THREAD

**Issue by basilv** [BCDevOps/backup-container#85]
The documentation is very unclear how to verify or restore backups created by a CronJob. There's no running pod to connect to for running the verify, versus the long-running backup container approach. 

Would it be just as easy as running a second CronJob to run the backup script in verification mode?

**Comment by WadeBarnes** [comment]
It should be.  The command would be `/backup.sh -s -v all`, rather than `/backup.sh -1`.

**Comment by basilv** [comment]
Including the -s option caused an error as it seemed to think it was running in scheduled mode and couldn't fine the schedule setting. Running /backup.sh -v all seemed to do the trick.

Also, I didn't need a separate CronJob, I just changed the one CronJob's command to:
                    - "/bin/bash"
                    - "-c"
                    - "/backup.sh -c && /backup.sh -1 && /backup.sh -v all"
