### ISSUE TITLE
Publish docker images for each release

### ISSUE THREAD

**Issue by WadeBarnes** [BCDevOps/backup-container#86]
Build and publish docker images for each release.  To include images for all supported databases.

Publish to either [bcgovimages](https://hub.docker.com/u/bcgovimages), or to the GitHub Container Registry.
- A number of BC Gov docker images are hosted on [bcgovimages](https://hub.docker.com/u/bcgovimages)
- An example of a project publishing to the GitHub Container Registry is [bcgov/von-network](https://github.com/bcgov/von-network); [von-network-base](https://github.com/bcgov/von-network/pkgs/container/von-network-base)

Builds and releases should be automated through GitHub Actions and be triggered on tags.

**Comment by patricksimonian** [comment]
I was just looking to build and push a version of the backup container into our docker org account but it looks like this is on the radar. I have some code examples of github action based pushes to docker on github release here. 

https://github.com/patricksimonian/just-ask/blob/main/.github/workflows/ci-docker-web.yaml

happy to make a PR for this

**Comment by WadeBarnes** [comment]
The first set of images was published with [Release 2.3.3](https://github.com/BCDevOps/backup-container/releases/2.3.3)
